# Generated by Django 4.2.30 on 2026-06-11 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockmovement',
            old_name='movement_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='file_number',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='related_docs',
        ),
        migrations.AlterField(
            model_name='product',
            name='belongto',
            field=models.CharField(choices=[('stock', 'In Stock'), ('factory', 'In Factory')], default='stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.productvariant'),
        ),
    ]
