# Generated by Django 4.2.30 on 2026-07-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_movement_type_stockmovement_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
