# Generated by Django 4.2.30 on 2026-09-02 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_productvariant_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_added', to=settings.AUTH_USER_MODEL),
        ),
    ]
