# Generated by Django 4.2.30 on 2026-06-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=20)),
                ('party_type', models.CharField(choices=[('customer', 'Customer'), ('factory', 'Factory')], max_length=20)),
                ('party_id', models.BigIntegerField()),
                ('reference_type', models.CharField(choices=[('customer_order', 'Customer Order'), ('purchase_order', 'Purchase Order'), ('expense', 'Expense')], max_length=30)),
                ('reference_id', models.BigIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
