# Generated by Django 4.2.30 on 2026-06-27 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_paymentrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='HawalaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hawala_accounts',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('Hawala', 'Hawala'), ('bank', 'Bank'), ('cheque', 'Cheque')], max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='party_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('factory', 'Factory')], max_length=100),
        ),
        migrations.CreateModel(
            name='HawalaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('supplier_payment', 'Supplier Payment'), ('customer_receipt', 'Customer Receipt'), ('withdrawal', 'Withdrawal'), ('adjustment', 'Adjustment')], max_length=30)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency_rate', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('other', 'Other')], default='cash', max_length=20)),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hawala_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounting.hawalaaccount')),
            ],
            options={
                'db_table': 'hawala_transactions',
                'ordering': ['-transaction_date', '-id'],
            },
        ),
    ]
