# Generated by Django 4.2.30 on 2026-06-24 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('investment', 'Investment'), ('withdrawal', 'Withdrawal'), ('profit_distribution', 'Profit Distribution')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency_rate', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('hawala', 'Hawala'), ('other', 'Other')], default='cash', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investors.investor')),
            ],
            options={
                'db_table': 'investor_transactions',
                'ordering': ['-transaction_date', '-id'],
            },
        ),
    ]
