# Generated by Django 4.2.30 on 2026-09-02 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investors', '0002_investortransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='investortransaction',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investor_transactions_added', to=settings.AUTH_USER_MODEL),
        ),
    ]
