# Generated by Django 4.2.30 on 2026-06-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='factory',
            name='gstin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='factory',
            name='supliercode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
