# Generated by Django 4.2.30 on 2026-06-21 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_factory_email_factory_gstin_factory_supliercode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={},
        ),
        migrations.AlterModelTable(
            name='purchaseorder',
            table=None,
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseorder')),
            ],
            options={
                'db_table': 'purchase_orders',
                'ordering': ['-id'],
            },
        ),
    ]
