# Generated by Django 4.2.30 on 2026-07-20 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_alter_purchaseorderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_orders', to='purchases.factory'),
        ),
    ]
