# Generated by Django 4.2.30 on 2026-06-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='exname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
